# General
title: Gogoratzen nauzuenetan
description: Ipuin ilustratuen bilduma
author:
  name: Iune Trecet Obeso
  email: contact@iune.info
  github: iunetrecet
  web: http://iune.info
timezone: "Europe/Paris"

# Collections
collections:
  - events
  - stories
  - stores


defaults:
  -
    scope:
      path: "index.html"
    values:
      ref: "index"
      lang: "eu"
  -
    scope:
      path: "index/eu.html"
    values:
      ref: "index"
      lang: "eu"
      permalink: "/eu/"
  -
    scope:
      path: "index/es.html"
    values:
      ref: "index"
      lang: "es"
      permalink: "/es/"
  -
    scope:
      path: "description"
    values:
      ref: "description"
  -
    scope:
      path: "group"
    values:
      ref: "group"
  -
    scope:
      path: "prologue"
    values:
      ref: "prologue"
  -
    scope:
      path: "nagore"
    values:
      ref: "nagore"
  -
    scope:
      path: "presentation"
    values:
      ref: "presentation"
