# General
title: Gogoratzen nauzuenetan
description: Ipuin ilustratuen bilduna
author:
  name: Iune Trecet Obeso
  email: contact@iune.info
  github: iunetrecet
  web: http://iune.info
timezone: "Europe/Paris
