# General
title: Gogoratzen nauzuenetan
description: Ipuin ilustratuen bilduma
author:
  name: Iune Trecet Obeso
  email: contact@iune.info
  github: iunetrecet
  web: http://iune.info
timezone: "Europe/Paris"

# Collections
collections:
  - events
  - stories
  - stores
  - descriptions
  - groups
  - prologues

