# General
title: Gogoratzen nauzuenetan
description: Ipuin ilustratuen bilduma
author:
  name: Iune Trecet Obeso
  email: contact@iune.info
  github: iunetrecet
  web: http://iune.info
timezone: "Europe/Paris"

# Collections
collections:
  - events
  - stories
  - stores


defaults:
  -
    scope:
      path: "description"
    values:
      ref: "description"
      permalink: "description"
  -
    scope:
      path: "group"
    values:
      ref: "group"
      permalink: "group"
  -
    scope:
      path: "prologue"
    values:
      ref: "prologue"
      permalink: "prologue"
  -
    scope:
      path: "nagore"
    values:
      ref: "nagore"
      permalink: "nagore"
  -
    scope:
      path: "presentation"
    values:
      ref: "presentation"
      permalink: "presentation"
